simulador 1_factorial.hex 1_factorial.out
simulador 1_fibonacci.hex 1_fibonacci.out
simulador 1_limits.hex 1_limits.out
simulador 1_recursive_factorial.hex 1_recursive_factorial.out
simulador 1_recursive_fibonacci.hex 1_recursive_fibonacci.out